# Generated by Django 4.1 on 2022-08-15 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_rating_description_rating_comment_rating_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='bname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
