# Generated by Django 4.1 on 2022-08-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_bname_rating_r_bname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_bname', models.CharField(blank=True, max_length=50)),
                ('c_sname', models.CharField(max_length=20)),
                ('c_fname', models.CharField(max_length=20)),
                ('c_email', models.CharField(max_length=30)),
                ('c_message', models.TextField(blank=True, max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('c_pnumber', models.CharField(max_length=20)),
            ],
        ),
    ]
