# Generated by Django 4.1 on 2022-09-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='avgreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg', models.FloatField()),
            ],
        ),
    ]
