# Generated by Django 4.1 on 2022-09-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_avgreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='avg',
            field=models.FloatField(default=0),
        ),
    ]
