# Generated by Django 4.1 on 2022-09-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rating_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='avg',
        ),
    ]
