# Generated by Django 4.1 on 2022-09-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_rating_avg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='avgreview',
        ),
    ]
